plugins:
  - jekyll-remote-theme

remote_theme: jeromelachaud/freelancer-theme
#theme: jekyll-theme-minimal
title: Maria Cosneanu - Portfolio 
description: Bookmark this to keep an eye on my project updates!
